### ISSUE TITLE
I'm getting an error that doesn't make sense

### ISSUE THREAD

**Issue by Thermatix** [edasque/cloudwatch2graphite#10]
I'm getting this error when I try to run the application:

```
Error : aws credential file is missing or invalid : ./conf/credentials.json
```
It doesn't make sense because the credentials are stored in `/etc/creds.json` and I'm passing it in as
`--credentials /etc/c2g/creds.json`; but just to make sure I copied the credentials file into the `./conf` folder relative to `cloudwatch2graphite.js` and renamed it to `credentials.json ` but it's still erroring.

Why is it bleating that it can't find the credentials?

**Comment by edasque** [comment]
Are you following the same syntax described in: https://github.com/edasque/cloudwatch2graphite/blob/master/conf/credentials.json.sample

**Comment by Thermatix** [comment]
*Sigh* leave it to someone else to point out one's own stupidity. Thanks, I now know what the problem was. I changed how the crednetials are stored but forgot that the hash that they use doesn't match the one that's used in your template. 
Specifically the keys are different, this is because the keys are used in another place as as well.
 any way, I forgot to account for that and didn't change the hash used for the credentials file generation.

Thank you.

**Comment by edasque** [comment]
Sure thing. FYI, we're in the middle of a nice rewrite of Cloudwatch2Graphite.
