### ISSUE TITLE
data output format not match?

### ISSUE THREAD

**Issue by hotsun** [edasque/cloudwatch2graphite#16]
Hi,

Sample output:
aws.dynamodb.rad_impressions.throttledrequests.updateitem.sum.count 28.0 1359407920
aws.elb.radimp.requestcount.sum.count 933.0 1359407920
aws.dynamodb.rad_impressions.consumedwritecapacityunits.sum.count 890.0 1359407920

I can get the data normally.

But from [https://github.com/etsy/statsd/#usage](https://github.com/etsy/statsd/#usage)
the usage is <metricname>:<value>|<type>
example:
echo "foo:1|c" | nc -u -w0 127.0.0.1 8125

So "node cw2graphite.js | nc host 2003" doesn't work.
Any advise?

**Comment by edasque** [comment]
Cloudwatch2graphite sends data directly to graphite, in your example you seem to be trying to send it to statsd? You could do that but you'd have to modify the application not change the output to using the ```metric:value|c``` syntax that statsd accepts

**Comment by hotsun** [comment]
It works. Thanks edasque.
