### ISSUE TITLE
Empty result for all the metrics

### ISSUE THREAD

**Issue by varmamahesh** [edasque/cloudwatch2graphite#5]
All the results of running the cw2graphite.js file spits empty results even though I know there is data available from cloudwatch. Basically, here is the output of running "node cw2graphite.js"

WARNING ! no data point available for metric........

Here is the snippet of metrics.json file

{
        "Namespace": "AWS/EC2",
        "MetricName": "CPUUtilization",
        "Statistics.member.1":"Average",
        "Unit": "Percent",
        "Dimensions.member.1.Name":"ImageId",
        "Dimensions.member.1.Value":"ami-xxxxxx",
        "Dimensions.member.2.Name":"InstanceId",
        "Dimensions.member.2.Value":"i-xxxxxx"
       }

Not sure if anyone else if facing this issue.

**Comment by edasque** [comment]
Have you tried the latest?

**Comment by edasque** [comment]
Closing as people seem to have no issue with the current software
