### ISSUE TITLE
Does not work with AWS instance IAM role

### ISSUE THREAD

**Issue by sabyasachi** [edasque/cloudwatch2graphite#8]
Is there a way to get it working with AWS instance IAM role? IAM users try to avoid putting AWS keys in code/configuration files.

**Comment by mansooralikkdn** [comment]
I have done a workaround. Normally it should take the credentials. But I was getting no region selected error. So I did not change the "REPLACE" part in the config for secret key and accesskey. 

ar config = require('./lib/readConfig.js').readCmdOptions();

// Now using the official Amazon Web Services SDK for Javascript
var AWS = require("aws-sdk");
var  AW = AWS.config.update({region: 'us-east-1'});
// We'll use the Cloudwatch API
var cloudwatch = new AWS.CloudWatch(AW);
